### ISSUE TITLE
someone unpublish 0.0.4 in npm?

### ISSUE THREAD

**Issue by imsobear** [efacilitation/gulp-modify#3]
Can't install 0.0.4 suddenly, and then:

```
➜  ~  npm info gulp-modify versions
[ '0.0.1', '0.0.2', '0.0.3', '0.0.5' ]

➜  ~  npm info gulp-modify time

{ modified: '2015-04-26T07:35:31.143Z',
  created: '2014-03-03T15:41:23.527Z',
  '0.0.1': '2014-03-03T15:41:23.527Z',
  '0.0.2': '2014-04-13T10:00:11.347Z',
  '0.0.3': '2014-04-13T10:04:56.201Z',
  '0.0.4': '2014-04-13T17:30:32.437Z',
  '0.0.5': '2015-04-26T07:35:31.143Z' }
```
someone unpublish 0.0.4 in npm? kidding me?

**Comment by alexlawrence** [comment]
Sorry, this was by accident. My fault. I messed up stuff. Can you just upgrade to 0.0.5?

**Comment by popomore** [comment]
Why do you publish with push tags? Can't match the published version to the commit.

**Comment by imsobear** [comment]
Of course i can upgrade to 0.0.5, But I think you should publish 0.0.4 now.

And maybe you should create tag for this repo~:)

**Comment by popomore** [comment]
@imsobear npm can't force publish since it exists, even it's unpublished.

**Comment by imsobear** [comment]
😭

**Comment by alexlawrence** [comment]
I´d really like to support you but I guess it is solved since you closed the issue. And in general: Try to be nice to each other. Sentences liking "kidding me?" doesn´t actually encourage the package maintainer to resolve your issue. Even if it was my mistake.

> Why do you publish without push tags? Can't match the published version to the commit.

Because we didn´t need it up until now.

**Comment by imsobear** [comment]
I'm sorry about that, just because the mistake is beyond my expectation.

:octocat:

**Comment by alexlawrence** [comment]
I understand that. Unpublishing is a really nasty thing. Sorry for any inconveniences. You can safely update from 0.0.4 to 0.0.5. The only that has changed is the readme.
